### ISSUE TITLE
[REQUEST] Add a Fullscreen switch to toolbar

### ISSUE THREAD

**Issue by KoleckOLP** [eclipsedteam/osu-trigen#14]
A fullscreen button or a Working Alt+Enter.

Alt+Enter currently fullscreens but with black bars. (Screenshot from a MS store build)
![image](https://user-images.githubusercontent.com/22729896/75778135-8863c800-5d57-11ea-8df8-b4ccc32c2496.png)

**Comment by KoleckOLP** [comment]
It actually just fullscreens the current window resolution.
![image](https://user-images.githubusercontent.com/22729896/75778443-18a20d00-5d58-11ea-8026-233ec6a4d24c.png)

**Comment by Tanza3D** [comment]
Will do.

**Comment by Tanza3D** [comment]
added switch but still running into black bars issue, am investigating

**Comment by Tanza3D** [comment]
sorted
