### ISSUE TITLE
Menu Tips

### ISSUE THREAD

**Issue by Tanza3D** [eclipsedteam/osu-trigen#15]
We're adding menu tips! Leave your suggestion in the comments and i'll try to add it in the next update!
![image](https://user-images.githubusercontent.com/33783503/76970869-6310b580-6924-11ea-872f-fcc289be2555.png)

**Comment by Tanza3D** [comment]
tip1  = "Seperate the background colour and triangle colour by enabling \"Seperate Pickers\" in the Colour Picker!";
        tip2  = "Replace the triangles with the \"Replace Tri\" option in the Tools panel!";
        tip3  = "Enable and disable panels at your leisure by using the toolbar! There's some extras there, too!";
        tip4  = "Make the triangles go left, right, up, or down by using the \"Triangle Rotation\" option in the toolbar!";
        tip5  = "Triangles looking bad? Try messing with the Colour Variance in the Advanced Options panel, accessible through the toolbar!";
        tip6  = "Not liking the default osu!trigen theme? Give the Theme Manager a whirl either using the preinstalled themes or custom themes!";
        tip7  = "Make sure to make the custom triangle sprite white for colour variance and custom colours to work properly!"; // Suggestion by @KoleckOLP
        tip8  = "Messed up the settings a bit too much? Just hit the Reset All button in the Tools panel and be good to go!";
        tip9  = "Found a bug? Why not report it using the Report Bug button in the Info panel?";
        tip10 = "Make sure to read up on the privacy policy found in the Info panel!";
        tip11 = "Want to replace the background? Try out the Replace BG button found in the Tools panel!";
        tip12 = "Want to hide the UI to use trigen in a stream? Just hit ESC and enjoy!";
        tip13 = "Want to change the colours of the triangles without them moving? Hit the pause button in the bottom right and enjoy!";
        tip14 = "You can save & load a Trigen Config using the save/load button found at the top of the Tools Panel to load again at a later time!";
        tip15 = "Just made a theme you really truly like? Save it and load it again at a later time! If you save into the themes folder, it'll show up in the list!";
        tip16 = "Fun fact! This entire project is Open Source on Github at @eclipsedteam! You can find the link also in the Info panel.";
        tip17 = "Did you know that there are hotkeys in osu!trigen? Check them out! https://github.com/eclipsedteam/osu-trigen/wiki/hotkeys";
        tip18 = "Bit confused about how osu!trigen works? Check out the wiki! https://github.com/eclipsedteam/osu-trigen/wiki";
        tip19 = "Have an idea for a menu tip? Drop a comment on the tip post! https://github.com/eclipsedteam/osu-trigen/issues/15";
        tip20 = "Most options you change only apply to newly spawned triangles. Please give them a minute!";

**Comment by yousef157** [comment]
how 'bout show some hotkeys that are useful

**Comment by Tanza3D** [comment]
could work, i'll see what i can do
