### ISSUE TITLE
[FEATURE] Save PNG path of background as well

### ISSUE THREAD

**Issue by Tanza3D** [eclipsedteam/osu-trigen#6]
When you save a config, it should probably save the path of the background, and load it as well. Instead of just saving the triangle.

**Comment by Tanza3D** [comment]
Got it saving, but have no clue to load it. @BradCubed please

**Comment by Tanza3D** [comment]
Am looking into this tomorrow

**Comment by ghost** [comment]
you could try something like writing a parser or if you're too lazy you could just https://assetstore.unity.com/packages/tools/advanced-ini-parser-23706

**Comment by Tanza3D** [comment]
actually did this like a week ago
